window.CSRFlows=(()=>{
 const R=window.CSRRules,E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),$=id=>document.getElementById(id),today=()=>new Date().toLocaleDateString('en-CA');let api;
 const uid=()=>crypto.randomUUID(),modal=(t,b)=>CSRWorkspace.modal(t,b),db=()=>api.db(),role=()=>R.role(api.user());
 const opts=(values,selected)=>(Array.isArray(values)?values:[]).map(v=>'<option '+(v===selected?'selected':'')+'>'+E(v)+'</option>').join('');
 const field=(name,label,type='text',value='',required=true)=>'<label>'+label+'<input name="'+name+'" type="'+type+'" value="'+E(value)+'" '+(required?'required':'')+'></label>';
 const select=(name,label,values,selected='')=>'<label>'+label+'<select name="'+name+'" required><option value="">Selecione</option>'+opts(values,selected)+'</select></label>';
 function people(name,label,onlyOperators=false){return '<label>'+label+'<select name="'+name+'" required><option value="">Selecione</option>'+((db().users||[]).filter(u=>u.active!==false&&(!onlyOperators||R.role(u)==='Operador')).map(u=>'<option value="'+E(u.id)+'">'+E(u.nome)+'</option>').join(''))+'</select></label>';}
 function hours(start,end,rest=0){if(!/^\d{2}:\d{2}$/.test(start||'')||!/^\d{2}:\d{2}$/.test(end||''))return 0;let a=start.split(':').map(Number),b=end.split(':').map(Number),n=b[0]*60+b[1]-a[0]*60-a[1];if(n<0)n+=1440;return Math.max(0,(n-rest)/60);}
 function staff(host,nav=()=>'',wire=()=>{}){
  const rank={Operador:1,Lider:2,Supervisor:3,Coordenador:4,Gerente:5,Administrador:6}[role()]||1;
  const canEditRecord=record=>rank>=3&&(record.date>=today()||rank>=4);
  host.innerHTML=nav()+'<section class="panel"><div class="ops-head"><div><h2>Efetivo do plantão</h2><p class="hint-text">Um registro por plantão e data. Abra um registro existente para gerar o texto ou editar.</p></div><button class="btn btn-primary" id="staff-new">Registrar novo efetivo</button></div><div class="route-toolbar"><input type="date" id="staff-filter-date" aria-label="Filtrar histórico por data"><button class="btn btn-secondary" id="staff-share-day">Gerar efetivo do dia</button></div><div id="staff-records"></div></section>';
  wire();
  function rows(){const filter=$('staff-filter-date').value;return (db().staffControls||[]).filter(s=>!filter||s.date===filter).slice().sort((a,b)=>String(b.date).localeCompare(String(a.date))||String(a.shift).localeCompare(String(b.shift)));}
  function share(s){const m=modal('Efetivo para compartilhar','<p>'+E(s.date)+' · '+E(s.shift)+'</p><textarea rows="14" readonly aria-label="Texto do efetivo"></textarea><button class="btn btn-primary" id="staff-copy">Copiar texto</button>');m.querySelector('textarea').value=R.staffText(s);$('staff-copy').onclick=async()=>{try{await navigator.clipboard.writeText(R.staffText(s));api.toast('Texto copiado.');}catch{m.querySelector('textarea').select();api.toast('Selecione e copie o texto.');}};}
  function draw(){
    const list=rows();
    $('staff-records').innerHTML=list.map(s=>'<article class="v58-staff-row"><div><h3>'+E(s.shift)+' · '+E(s.date)+'</h3><p>Supervisor: '+E(s.supervisor||s.coordinator)+' · Líder: '+E(s.leader||s.analyst)+'</p><small>'+(s.operators||[]).length+'/'+(s.required||11)+' operadores · '+(s.absences||[]).length+' faltas</small></div><div class="actions-row"><button class="btn btn-secondary" data-share="'+E(s.id)+'">Gerar texto</button>'+(canEditRecord(s)?'<button class="btn btn-secondary" data-staff-edit="'+E(s.id)+'">Editar</button>':'')+'</div></article>').join('')||'<p class="empty-state">Nenhum efetivo registrado nesta data.</p>';
    host.querySelectorAll('[data-share]').forEach(b=>b.onclick=()=>share((db().staffControls||[]).find(s=>s.id===b.dataset.share)));
    host.querySelectorAll('[data-staff-edit]').forEach(b=>b.onclick=()=>openForm((db().staffControls||[]).find(s=>s.id===b.dataset.staffEdit)));
  }
  function openForm(existing){
    if(existing&&!canEditRecord(existing))return api.toast('Este efetivo não pode mais ser editado pelo seu perfil.');
    const settings=db().tabSettings||{},shifts=(Array.isArray(settings.plantoes)&&settings.plantoes.length?settings.plantoes:['Diurno','Noturno','Comercial']);
    const baseNames=[...(db().operationalBases||[]).filter(b=>b.active!==false).map(b=>b.name),...(Array.isArray(settings.clientes)?settings.clientes:[])].filter((name,index,list)=>name&&list.indexOf(name)===index);
    const selectedDate=existing?.date||today(),minimum=rank>=4?'':' min="'+today()+'"';
    const m=modal(existing?'Editar efetivo':'Registrar efetivo','<form id="staff-form"><div class="form-grid two"><label>Data<input type="date" name="date" required value="'+E(selectedDate)+'"'+minimum+'></label>'+select('shift','Plantão',shifts,existing?.shift||'')+field('supervisor','Supervisor','text',existing?.supervisor||existing?.coordinator||'')+field('leader','Líder','text',existing?.leader||existing?.analyst||'')+field('required','Operadores necessários','number',existing?.required||11)+field('support','Apoio','text',existing?.support||'',false)+'</div><h3>Operadores presentes</h3><div id="staff-present"></div><button type="button" class="btn btn-secondary" data-add="present">Adicionar operador</button><h3>Faltas</h3><div id="staff-absent"></div><button type="button" class="btn btn-secondary" data-add="absent">Informar falta</button><label>Possui hora extra?<select id="staff-extra-toggle"><option value="no">Não</option><option value="yes">Sim</option></select></label><div id="staff-extra-box" hidden><div id="staff-extra"></div><button type="button" class="btn btn-secondary" data-add="extra">Adicionar hora extra</button></div><button type="submit" class="btn btn-primary">'+(existing?'Salvar edição':'Salvar efetivo')+'</button></form>');
    function add(kind,data={}){const row=document.createElement('div');row.className='v59-staff-line';row.dataset.kind=kind;row.innerHTML=people('user','Colaborador',kind==='present')+(kind==='present'?select('base','Base',baseNames):kind==='absent'?field('reason','Motivo da falta')+select('certificate','Atestado',['Sem atestado','Com atestado','Aguardando atestado'],data.certificate||'Sem atestado'):field('start','Chegada','time',data.start||'')+field('end','Saída','time',data.end||'')+field('breakMinutes','Intervalo (min)','number',data.breakMinutes??60))+'<button type="button" aria-label="Remover linha">×</button>';row.querySelector('[name="user"]').value=data.userId||data.user||'';if(row.querySelector('[name="base"]'))row.querySelector('[name="base"]').value=data.base||'';if(row.querySelector('[name="reason"]'))row.querySelector('[name="reason"]').value=data.reason||'';row.querySelector('button').onclick=()=>row.remove();$('staff-'+kind).append(row);}
    const linkedAbsences=existing?(db().absences||[]).filter(a=>a.staffId===existing.id):[];
    (existing?.operators?.length?existing.operators:[{}]).forEach(add.bind(null,'present'));
    linkedAbsences.forEach(add.bind(null,'absent'));
    m.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>add(b.dataset.add));
    $('staff-extra-toggle').onchange=function(){$('staff-extra-box').hidden=this.value!=='yes';$('staff-extra-box').querySelectorAll('input,select').forEach(x=>x.disabled=this.value!=='yes');if(this.value==='yes'&&!$('staff-extra').children.length)add('extra');};
    $('staff-form').onsubmit=async event=>{
      event.preventDefault();const form=event.currentTarget,values=Object.fromEntries(new FormData(form)),readRows=kind=>Array.from($('staff-'+kind).children).map(row=>Object.fromEntries(Array.from(row.querySelectorAll('input,select')).map(input=>[input.name,input.value]))),present=readRows('present'),absent=readRows('absent'),extra=$('staff-extra-toggle').value==='yes'?readRows('extra'):[];
      if(values.date<today()&&rank<4)return api.toast('Efetivos de datas anteriores só podem ser registrados por Coordenador ou superior.');
      if((db().staffControls||[]).some(s=>s.id!==existing?.id&&s.date===values.date&&s.shift===values.shift))return api.toast('Já existe um efetivo para este plantão nesta data. Abra o registro existente para editar.');
      if(!present.length||present.some(item=>!item.user||!item.base))return api.toast('Informe ao menos um operador presente e sua base.');
      const unique=[...present,...absent].map(item=>item.user).filter(Boolean);if(new Set(unique).size!==unique.length)return api.toast('Um colaborador não pode constar como presente e ausente ao mesmo tempo.');
      if(extra.some(item=>!hours(item.start,item.end,Number(item.breakMinutes))||Number(item.breakMinutes)<0))return api.toast('Revise os horários e o intervalo das horas extras.');
      const userName=id=>{const found=(db().users||[]).find(user=>user.id===id);return found?found.nome:'Usuário não encontrado';};
      const record={id:existing?.id||uid(),date:values.date,shift:values.shift,supervisor:values.supervisor,leader:values.leader,coordinator:values.supervisor,analyst:values.leader,required:Number(values.required),support:values.support,operators:present.map(item=>({userId:item.user,name:userName(item.user),base:item.base})),absences:absent.map(item=>userName(item.user)),vacationNames:existing?.vacationNames||[],extras:extra.length?extra.map(item=>({name:userName(item.user),start:item.start,end:item.end})):existing?.extras||[],by:existing?.by||api.user().nome,at:existing?.at||Date.now(),updatedBy:api.user().nome,updatedAt:Date.now()};
      const absenceRecords=absent.map((item,index)=>({id:linkedAbsences[index]?.id||uid(),staffId:record.id,userId:item.user,name:userName(item.user),date:record.date,shift:record.shift,reason:item.reason,certificate:item.certificate||'Sem atestado',by:linkedAbsences[index]?.by||api.user().nome,at:linkedAbsences[index]?.at||Date.now()}));
      const button=form.querySelector('[type="submit"]');button.disabled=true;
      try{
        if(api.remote())await api.saveStaff(record,absenceRecords);else{const controls=db().staffControls||[];const position=controls.findIndex(s=>s.id===record.id);if(position>=0)controls[position]=record;else controls.push(record);db().staffControls=controls;db().absences=(db().absences||[]).filter(a=>a.staffId!==record.id).concat(absenceRecords);}
        extra.forEach(item=>(db().overtime||=[]).push({id:uid(),staffId:record.id,userId:item.user,name:userName(item.user),date:record.date,start:item.start,end:item.end,breakMinutes:Number(item.breakMinutes),hours:hours(item.start,item.end,Number(item.breakMinutes)),by:api.user().nome,at:Date.now()}));
        api.save();m.close();m.remove();draw();api.toast(existing?'Efetivo atualizado.':'Efetivo registrado.');
      }catch(error){api.toast(error.message||'Não foi possível salvar o efetivo.');}finally{button.disabled=false;}
    };
  }
  $('staff-new').onclick=()=>openForm(null);
  $('staff-filter-date').onchange=draw;
  $('staff-share-day').onclick=()=>{const list=rows();if(!list.length)return api.toast('Nenhum efetivo encontrado na data selecionada.');if(list.length===1)return share(list[0]);const m=modal('Escolha o plantão',list.map(s=>'<button class="btn btn-secondary" data-pick="'+E(s.id)+'">'+E(s.shift)+'</button>').join(''));m.querySelectorAll('[data-pick]').forEach(b=>b.onclick=()=>share(list.find(s=>s.id===b.dataset.pick)));};
  draw();
 }
 function early(host){host.innerHTML='<section class="panel"><h1>Saída antecipada</h1><form id="early-form"><div class="form-grid two">'+people('userId','Colaborador')+field('date','Data','date',today())+field('start','Chegada','time')+field('end','Saída','time')+field('reason','Motivo')+'</div><button class="btn btn-primary">Registrar saída</button></form><h2>Histórico</h2><div id="early-list"></div></section>';function draw(){$('early-list').innerHTML=(db().earlyDepartures||[]).slice().reverse().map(x=>'<article class="v58-staff-row"><div><b>'+E(x.name)+'</b><p>'+E(x.date)+' · '+E(x.start)+'–'+E(x.end)+'</p><p>'+E(x.reason)+'</p></div></article>').join('')||'<p>Nenhuma saída registrada.</p>';}$('early-form').onsubmit=e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget));if(!hours(v.start,v.end))return api.toast('Confira os horários.');(db().earlyDepartures||=[]).push({...v,id:uid(),name:db().users.find(u=>u.id===v.userId).nome,by:api.user().nome,at:Date.now()});api.save();e.currentTarget.reset();draw();};draw();}
 async function transition(a,linked,kind,reason,closing){if(linked&&!closing)linked.alertId=a.id;const next={...a,history:[...(a.history||[])]};if(closing){next.status='Tratado';next.closedAt=Date.now();next.closedBy=api.user().nome;next.treatment=reason;if(linked)linked={...linked,status:kind==='sinistro'?'Encerrado':'Encerrada',closingReason:reason,closedAt:next.closedAt,closedBy:next.closedBy};}else{next.linkedType=kind;next.linkedId=linked.id;next.status='Pendente';}next.history.push({at:Date.now(),by:api.user().nome,note:reason,action:closing?'Encerrado':'Encaminhado para '+kind,linked:linked?{...linked}:null});if(api.remote())await api.commit(next,linked,kind,closing);Object.assign(a,next);if(linked){const list=kind==='sinistro'?db().sinistros:db().prontaResposta,current=list.find(x=>x.id===linked.id);if(current)Object.assign(current,linked);else list.push(linked);}api.save();api.toast(closing?'Alerta e atendimento encerrados.':'Atendimento vinculado ao alerta.');}
 function finish(a,done=()=>{}){if(!a||a.status!=='Pendente')return;const rank=R.roles.indexOf(role());if(rank<(a.linkedType==='sinistro'?2:1))return api.toast(a.linkedType==='sinistro'?'Somente supervisão ou superior pode finalizar este sinistro.':'Somente liderança ou superior pode finalizar.');const linked=a.linkedId?(a.linkedType==='sinistro'?db().sinistros:db().prontaResposta).find(x=>x.id===a.linkedId):null;if(a.linkedId&&!linked)return api.toast('O atendimento vinculado não está disponível. Confira sua permissão e sincronize novamente.');
 if(linked){const m=modal('Finalizar '+(a.linkedType==='sinistro'?'sinistro':'pronta resposta'),'<div class="v59-linked-summary"><p><b>Equipe:</b> '+E(linked.equipe||linked.reportedBy||'—')+'</p><p><b>Status:</b> '+E(linked.status)+'</p><p><b>Acionamento:</b> '+E(linked.data)+' '+E(linked.horario)+'</p><p><b>Descrição:</b> '+E(linked.description||linked.motivo||linked.relato)+'</p></div>'+closingForm());wireClose(m,a,linked,a.linkedType,done);return;}
 const m=modal('Tratativa do alerta','<div class="v59-actions"><button data-result="resolved">Resolvido</button><button data-result="pronta">Pronta resposta</button><button data-result="sinistro">Sinistro</button></div>');m.querySelectorAll('[data-result]').forEach(b=>b.onclick=()=>{m.close();m.remove();if(b.dataset.result==='resolved'){const n=modal('Resolver alerta',closingForm());wireClose(n,a,null,'',done);}else if(b.dataset.result==='pronta')api.pr(a,done);else{if(!api.perm('sinistro_create'))return api.toast('Seu perfil não possui permissão para registrar sinistro.');window.csrIncidentAlert=a.id;api.incident();}});}
 function closingForm(){return '<form id="flow-close"><label>Motivo da finalização<textarea name="reason" required minlength="3" rows="4"></textarea></label><button class="btn btn-primary">Finalizar</button></form>';}
 function wireClose(m,a,l,k,done){m.querySelector('form').onsubmit=async e=>{e.preventDefault();const b=e.currentTarget.querySelector('button');b.disabled=true;try{await transition(a,l,k,e.currentTarget.elements.reason.value.trim(),true);m.close();m.remove();done();}catch(e){api.toast(e.message||'Não foi possível finalizar.');}finally{b.disabled=false;}};}
 function prForm(a,done){const m=modal('Acionar pronta resposta','<form id="flow-pr"><div class="form-grid two">'+field('equipe','Equipe')+field('data','Data do acionamento','date',today())+field('horario','Horário','time',new Date().toTimeString().slice(0,5))+field('cavalo','Placa','text',a.placa)+field('sm','SM','text',a.sm||'',false)+field('operacao','Base','text',a.base)+select('status','Status',['Acionada','Em deslocamento','No local','Em atendimento'])+'</div><label>Motivo / descrição<textarea name="motivo" required rows="4"></textarea></label><button class="btn btn-primary">Salvar acionamento</button></form>');m.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,b=f.querySelector('button');b.disabled=true;try{const v={...Object.fromEntries(new FormData(f)),id:uid(),alertId:a.id,solicitanteNome:api.user().nome,createdAt:Date.now()};v.pronta=v.equipe;await transition(a,v,'pronta',v.motivo,false);m.close();m.remove();done();}catch(e){api.toast(e.message);}finally{b.disabled=false;}};}
 async function incidentSaved(record){const a=db().operationalOccurrences.find(x=>x.id===window.csrIncidentAlert);if(!a)return false;if(a.linkedId)throw Error('Este alerta já possui atendimento vinculado.');record.alertId=a.id;await transition(a,record,'sinistro',record.description,false);window.csrIncidentAlert=null;return true;}
 async function upload(file){if(!api.remote())return ChecklistMedia.upload(file,{local:true});if(!/^(image\/(jpeg|png|webp)|audio\/)/.test(file.type)||file.size>25*1024*1024)throw Error('Use imagem ou áudio de até 25 MB.');const path=api.user().id+'/'+uid(),r=await api.client().storage.from('sinistro-files').upload(path,file,{contentType:file.type});if(r.error)throw r.error;return {name:file.name,type:file.type,size:file.size,path,bucket:'sinistro-files'};}
 function media(host,files){(files||[]).forEach(async f=>{if(!f.bucket)return ChecklistMedia.render(host,f,{local:true});const box=document.createElement('div');host.append(box);const r=await api.client().storage.from(f.bucket).createSignedUrl(f.path,300);if(r.error){box.textContent='Não foi possível carregar '+f.name;return;}const el=document.createElement(f.type.startsWith('image/')?'img':'audio');el.src=r.data.signedUrl;el.alt=f.name;el.controls=true;el.style.maxWidth='100%';box.append(el);});}
 function analytics(host){const users=db().users.filter(u=>u.active!==false&&(role()==='Administrador'||u.managerId===api.user().id));host.innerHTML='<section class="panel"><h1>Análise de dúvidas</h1><label>Operador<select id="analysis-user"><option value="">Selecione um colaborador</option>'+users.map(u=>'<option value="'+E(u.id)+'">'+E(u.nome)+'</option>').join('')+'</select></label><div id="analysis-detail"><p>Escolha um colaborador para consultar suas dúvidas.</p></div></section>';$('analysis-user').onchange=function(){const q=(db().aiQueries||[]).filter(q=>q.userId===this.value&&users.some(u=>u.id===q.userId)),counts={};q.forEach(x=>{const text=x.text.trim();counts[text]=(counts[text]||0)+1;});$('analysis-detail').innerHTML='<h2>'+q.length+' consultas</h2>'+Object.entries(counts).sort((a,b)=>b[1]-a[1]).map(([t,n])=>'<article class="v58-staff-row"><p>'+E(t)+'</p><b>'+n+'×</b></article>').join('');};}
 function answer(text){const norm=t=>String(t).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase(),tokens=norm(text).split(/\W+/).filter(w=>w.length>3&&!['como','para','qual','quais','preciso','sobre','fazer','esta','esse','essa'].includes(w)),manuals=Object.values(window.TECH_MANUALS?.items||{}).map(m=>({title:m.title,text:(m.content||[]).filter(p=>p.type==='text').map(p=>p.text).join('\n'),date:m.addedAt||db().tabSettings.manualDates?.[m.key]})).concat((db().aiKnowledge||[]).filter(x=>x.text).map(x=>({title:x.name,text:x.text,date:x.at})));const ranked=manuals.map(m=>({...m,score:tokens.reduce((n,t)=>n+(norm(m.title).includes(t)?5:0)+(norm(m.text).includes(t)?1:0),0)})).filter(m=>m.score>0&&m.text).sort((a,b)=>b.score-a.score).slice(0,2);if(!ranked.length)return 'Não encontrei um trecho correspondente nos manuais disponíveis. Informe a tecnologia e o procedimento ou alerta que deseja consultar. Não vou atribuir orientações a um manual sem localizar a fonte.';return ranked.map(m=>{const paragraphs=m.text.split(/\n+/).filter(Boolean),hits=paragraphs.map((p,i)=>({p,i,score:tokens.reduce((n,t)=>n+(norm(p).includes(t)?1:0),0)})).sort((a,b)=>b.score-a.score).slice(0,3).sort((a,b)=>a.i-b.i);return 'Trechos do procedimento cadastrado:\n\n'+hits.map(x=>x.p).join('\n\n')+'\n\nInformações tiradas do manual: '+m.title+'\nData de inclusão: '+(m.date?new Date(m.date).toLocaleDateString('pt-BR'):'não informada no cadastro original')+'.';}).join('\n\n────────\n\n');}
 function dashboard(host){const old=host.querySelector('.v55-active-panel');if(!old)return;const open=db().operationalOccurrences.filter(a=>a.status==='Pendente'),pr=db().prontaResposta.filter(p=>!['Encerrada','Encerrado','Finalizada','Cancelada'].includes(p.status));old.outerHTML='<div class="v59-tracking">'+[['Prontas ativas no plantão',pr,'pronta-resposta'],['Alertas em acompanhamento',open,'central-ocorrencias']].map(([title,list,route])=>'<section class="panel"><header><h2>'+title+' <span>— '+list.length+'</span></h2><div><button data-scroll="-1" aria-label="Anterior">‹</button><button data-scroll="1" aria-label="Próximo">›</button></div></header><div class="v59-rail">'+(list.map(x=>'<button data-open="'+E(route)+'" data-alert="'+(route==='central-ocorrencias'?E(x.id):'')+'">'+(route==='central-ocorrencias'?api.dot(x):'<span class="v58-alert-dot pronta"></span>')+'<span><b>'+E(x.placa||x.cavalo||x.sm||'Sem placa')+'</b><small>'+E(x.kind||x.equipe||x.status)+'</small></span></button>').join('')||'<p>Nenhum registro ativo no momento.</p>')+'</div></section>').join('')+'</div>';host.querySelectorAll('[data-scroll]').forEach(b=>b.onclick=()=>b.closest('section').querySelector('.v59-rail').scrollBy({left:Number(b.dataset.scroll)*260,behavior:'smooth'}));host.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{if(b.dataset.alert){const a=db().operationalOccurrences.find(a=>a.id===b.dataset.alert);finish(a,()=>api.refresh());}else api.navigate(b.dataset.open);});const tracking=host.querySelector('.v59-tracking'),metrics=host.querySelector('.v55-metric-grid');if(tracking&&metrics)metrics.after(tracking);const pending=(db().checklists||[]).filter(c=>c.status==='Pendente').length,total=(db().checklists||[]).length,card=document.createElement('section');card.className='panel v59-pending';card.innerHTML='<h2>Checklists pendentes</h2><strong>'+pending+'</strong><div class="v59-progress"><i style="width:'+(total?pending/total*100:0)+'%"></i></div><small>'+pending+' de '+total+' registros aguardam conclusão</small>';host.querySelector('.v58-chart-grid')?.append(card);}
 function incidentDetails(item){const m=modal('Sinistro · '+(item.placa||''),'<p><b>'+E(item.status)+'</b> · '+E(item.data)+' '+E(item.horario)+'</p><p>'+E(item.description||item.relato)+'</p>'+(item.closingReason?'<h3>Finalização</h3><p>'+E(item.closingReason)+'</p>':'')+'<div id="incident-attachments"></div>'+(item.alertId&&item.status!=='Encerrado'?'<button class="btn btn-primary" id="incident-finish">Finalizar alerta e sinistro</button>':''));media($('incident-attachments'),item.attachments);if($('incident-finish'))$('incident-finish').onclick=()=>{m.close();m.remove();finish(db().operationalOccurrences.find(a=>a.id===item.alertId),()=>api.refresh());};}
 function alertHistory(host,rows){host.querySelectorAll('tr').forEach((tr,i)=>{const a=rows[i];if(!a)return;const b=document.createElement('button');b.className='btn btn-secondary btn-sm';b.textContent='Histórico';tr.lastElementChild.append(b);b.onclick=()=>{const m=modal('Histórico · '+(a.placa||a.sm||'Alerta'),'<p>'+E(a.kind)+' · '+E(a.status)+'</p>'+ (a.history||[]).map(h=>'<article class="v59-history"><b>'+E(h.action||h.to||'Registro')+'</b><small>'+new Date(h.at).toLocaleString('pt-BR')+' · '+E(h.by)+'</small><p>'+E(h.note)+'</p>'+(h.linked?'<p>Equipe: '+E(h.linked.equipe||h.linked.reportedBy||'—')+' · Status: '+E(h.linked.status)+'<br>Acionamento: '+E(h.linked.data)+' '+E(h.linked.horario)+'</p><p>'+E(h.linked.motivo||h.linked.description||h.linked.relato)+'</p>':'')+'</article>').join(''));};});}
 function prDetails(item,done){const a=db().operationalOccurrences.find(a=>a.id===item.alertId);if(item.status!=='Encerrada')return finish(a,done);modal('Histórico de pronta resposta','<p><b>Equipe:</b> '+E(item.equipe||item.pronta)+'</p><p>'+E(item.status)+' · '+E(item.data)+' '+E(item.horario)+'</p><p>'+E(item.motivo)+'</p><h3>Motivo da finalização</h3><p>'+E(item.closingReason)+'</p>');}
 function manualEditor(){const host=$('ai-tab-config');if(!host||$('manual-provenance'))return;const section=document.createElement('section');section.className='panel';section.id='manual-provenance';section.innerHTML='<h3>Fontes do assistente</h3><p>Cadastre a data original de inclusão dos manuais. Para documentos em imagem ou PDF, acrescente o procedimento em texto para permitir consulta com fonte.</p><form id="manual-date-form">'+select('manual','Manual existente',Object.values(window.TECH_MANUALS?.items||{}).map(m=>m.title))+field('date','Data original de inclusão','date')+'<button class="btn btn-secondary">Salvar data do manual</button></form><form id="manual-text-form">'+field('title','Nome do manual')+field('date','Data de inclusão','date',today())+'<label>Procedimento em texto<textarea name="text" required rows="5"></textarea></label><button class="btn btn-primary">Adicionar fonte de consulta</button></form>';host.append(section);$('manual-date-form').onsubmit=e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget)),m=Object.values(window.TECH_MANUALS.items).find(m=>m.title===v.manual);(db().tabSettings.manualDates||={})[m.key]=v.date+'T12:00:00';api.save();api.toast('Data da fonte atualizada.');};$('manual-text-form').onsubmit=e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget));db().aiKnowledge.push({id:uid(),name:v.title,text:v.text,at:new Date(v.date+'T12:00:00').getTime(),type:'text/plain',by:api.user().nome,status:'Disponível para consulta'});api.save();e.currentTarget.reset();api.toast('Fonte adicionada.');};}
 return {init:a=>api=a,staff,early,finish,transition,incidentSaved,upload,media,analytics,answer,dashboard,hours,incidentDetails,alertHistory,prDetails,manualEditor};
})();
