/* Scoped enhancements for the existing operational workspace. */
window.CSRWorkspace=(function(){
  const R=window.CSRRules,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const $=id=>document.getElementById(id),date=()=>new Date().toLocaleDateString('en-CA'),opts=(a,selected)=>a.map(v=>'<option '+(v===selected?'selected':'')+'>'+esc(v)+'</option>').join('');
  let api;
  function init(ctx){api=ctx;}
  function modal(title,body){document.getElementById('v58-modal')?.remove();const el=document.createElement('dialog');el.id='v58-modal';el.className='v58-dialog';el.innerHTML='<header><h2>'+esc(title)+'</h2><button type="button" aria-label="Fechar">×</button></header>'+body;document.body.append(el);el.querySelector('header button').onclick=()=>{el.close();el.remove();};el.showModal();return el;}
  function bars(rows){const max=Math.max(1,...rows.map(r=>r[1]));return rows.length?rows.map(([label,value])=>'<div class="v58-bar"><span>'+esc(label)+'</span><i><b style="width:'+value/max*100+'%"></b></i><strong>'+value+'</strong></div>').join(''):'<p class="hint-text">Ainda não há registros neste período.</p>';}
  function group(rows,key){const map={};rows.forEach(r=>{const k=key(r)||'Não informado';map[k]=(map[k]||0)+1;});return Object.entries(map).sort((a,b)=>b[1]-a[1]);}
  function dashboard(host){const a=api.db().operationalOccurrences||[];const grid=document.createElement('div');grid.className='v58-chart-grid';const hours=Array.from({length:12},(_,i)=>{const h=i*2;return [String(h).padStart(2,'0')+'h',a.filter(x=>x.date===date()&&Number((x.time||'').slice(0,2))>=h&&Number((x.time||'').slice(0,2))<h+2).length];});grid.innerHTML='<section class="panel"><h2>Alertas por tipo</h2>'+bars(group(a,x=>x.kind).slice(0,6))+'</section><section class="panel"><h2>Resultado dos contatos</h2>'+bars(group(a,x=>x.contact))+'</section><section class="panel"><h2>Volume por horário · hoje</h2><div class="v58-histogram">'+hours.map(([h,n])=>'<div><b>'+n+'</b><i style="height:'+Math.max(2,n/Math.max(1,...hours.map(x=>x[1]))*120)+'px"></i><span>'+h+'</span></div>').join('')+'</div></section><section class="panel"><h2>Criticidade dos alertas ativos</h2>'+bars(group(a.filter(x=>x.status==='Pendente'),x=>R.alertState(x,api.db().tabSettings.alertRules).criticality))+'</section>';host.querySelector('.v55-active-panel')?.before(grid);}
  function alertRules(host){const db=api.db();db.tabSettings.alertRules=db.tabSettings.alertRules||{};host.innerHTML='<section class="panel"><h2>Tipos de alerta e encerramento</h2><p class="hint-text">O prazo começa no registro do alerta. Amarelo indica os últimos 2 minutos. Sem regra habilitada, o alerta aguarda encerramento manual.</p><form id="rule-add" class="route-toolbar"><input name="name" required aria-label="Nome do alerta" placeholder="Nome do novo alerta"><button class="btn btn-primary">Adicionar tipo</button></form><div id="rule-list"></div></section>';function draw(){$('rule-list').innerHTML=(db.tabSettings.alertas||[]).map((name,i)=>{const r=db.tabSettings.alertRules[name]||{};return '<form class="v58-rule" data-index="'+i+'"><h3>'+esc(name)+'</h3><label>Criticidade<select name="criticality">'+opts(['Normal','Atenção','Crítico'],r.criticality||'Normal')+'</select></label><label><input type="checkbox" name="success" '+(r.success?'checked':'')+'> Encerrar após 10 min · contato com sucesso</label><label><input type="checkbox" name="failure" '+(r.failure?'checked':'')+'> Encerrar após 10 min · contato sem sucesso</label><button class="btn btn-primary">Salvar regra</button><button class="btn btn-secondary" type="button" data-remove="'+i+'">Excluir tipo</button></form>';}).join('');host.querySelectorAll('.v58-rule').forEach(f=>{f.onsubmit=e=>{e.preventDefault();const name=db.tabSettings.alertas[Number(f.dataset.index)];db.tabSettings.alertRules[name]={criticality:f.elements.criticality.value,success:f.elements.success.checked,failure:f.elements.failure.checked};api.save();api.toast('Regra salva.');};});host.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{db.tabSettings.alertas.splice(Number(b.dataset.remove),1);api.save();draw();});}$('rule-add').onsubmit=e=>{e.preventDefault();const input=e.currentTarget.elements.name,name=input.value.trim();if(name&&!db.tabSettings.alertas.includes(name)){db.tabSettings.alertas.push(name);api.save();draw();}input.value='';};draw();}
  function staff(host,nav,wire){const db=api.db();host.innerHTML=nav()+'<section class="panel"><div class="ops-head"><div><h2>Efetivo do plantão</h2><p class="hint-text">Registre uma vez e gere o texto para compartilhar.</p></div><button class="btn btn-primary" id="v58-staff-new">Registrar novo efetivo</button></div><div class="route-toolbar"><input type="date" id="v58-staff-date" aria-label="Filtrar data" value="'+date()+'"><button class="btn btn-secondary" id="v58-staff-share">Gerar efetivo do dia</button></div><div id="v58-staff-list"></div></section>';wire();function share(s){const m=modal('Efetivo para compartilhar','<p>'+esc(s.date)+' · '+esc(s.shift)+'</p><textarea rows="12" readonly aria-label="Texto do efetivo"></textarea><button class="btn btn-primary" id="v58-copy">Copiar texto</button>');m.querySelector('textarea').value=R.staffText(s);$('v58-copy').onclick=async()=>{try{await navigator.clipboard.writeText(R.staffText(s));api.toast('Texto copiado.');}catch{m.querySelector('textarea').select();api.toast('Selecione e copie o texto.');}};}function rows(){return (db.staffControls||[]).filter(s=>!$('v58-staff-date').value||s.date===$('v58-staff-date').value).slice().reverse();}function draw(){$('v58-staff-list').innerHTML=rows().map(s=>'<article class="v58-staff-row"><div><h3>'+esc(s.shift)+' · '+esc(s.date)+'</h3><p>Supervisor: '+esc(s.supervisor||s.coordinator)+' · Líder: '+esc(s.leader||s.analyst)+'</p><small>'+s.operators.length+'/'+(s.required||11)+' operadores · '+(s.absences||[]).length+' faltas</small></div><button class="btn btn-secondary" data-share="'+esc(s.id)+'">Gerar texto</button></article>').join('')||'<p class="empty-state">Nenhum efetivo registrado nesta data.</p>';host.querySelectorAll('[data-share]').forEach(b=>b.onclick=()=>share(db.staffControls.find(s=>s.id===b.dataset.share)));}$('v58-staff-date').onchange=draw;$('v58-staff-share').onclick=()=>{const r=rows();if(!r.length)return api.toast('Registre o efetivo da data selecionada.');if(r.length===1)return share(r[0]);const m=modal('Escolha o plantão',r.map(s=>'<button class="btn btn-secondary" data-pick="'+esc(s.id)+'">'+esc(s.shift)+'</button>').join(''));m.querySelectorAll('[data-pick]').forEach(b=>b.onclick=()=>share(r.find(s=>s.id===b.dataset.pick)));};
    $('v58-staff-new').onclick=()=>{const m=modal('Registrar efetivo','<form id="v58-staff-form"><div class="form-grid two"><label>Data<input type="date" name="date" required value="'+date()+'"></label><label>Plantão<select name="shift" required><option value="">Selecione</option>'+opts(db.tabSettings.plantoes||[])+'</select></label><label>Supervisor<input name="supervisor" required></label><label>Líder<input name="leader" required></label><label>Operadores necessários<input name="required" type="number" min="1" value="11" required></label><label>Apoio<input name="support"></label></div><h3>Operadores presentes</h3><div id="v58-operators"></div><button class="btn btn-secondary" id="v58-add-op" type="button">Adicionar operador</button><label>Faltas · nomes separados por vírgula<input name="absences"></label><label>Pendências<textarea name="notes" rows="2"></textarea></label><button class="btn btn-primary">Salvar efetivo</button></form>');function add(){const row=document.createElement('div');row.className='operator-row';row.innerHTML='<input aria-label="Nome do operador" required><select aria-label="Base" required><option value="">Base</option>'+opts(db.tabSettings.clientes||[])+'</select><button type="button" aria-label="Remover operador">×</button>';row.querySelector('button').onclick=()=>row.remove();$('v58-operators').append(row);}add();$('v58-add-op').onclick=add;$('v58-staff-form').onsubmit=e=>{e.preventDefault();const f=e.currentTarget,v=Object.fromEntries(new FormData(f));const operators=Array.from($('v58-operators').children).map(r=>({name:r.querySelector('input').value.trim(),base:r.querySelector('select').value}));if(!operators.length)return api.toast('Informe os operadores presentes.');const s={...v,id:'staff-'+crypto.randomUUID(),required:Number(v.required),absences:v.absences.split(',').map(s=>s.trim()).filter(Boolean),operators,coordinator:v.supervisor,analyst:v.leader,by:api.user().nome,at:Date.now()};db.staffControls.push(s);api.save();m.close();m.remove();draw();api.toast('Efetivo registrado.');};};draw();
  }
  function guide(host){
    const pages=api.pages().filter(p=>api.perms()[p.perm]&&(p.id!=='duvidas-equipe'||R.role(api.user())!=='Operador')&&!['perfil','menu','documentacao'].includes(p.id));
    const docs={
      dashboard:{intro:'Consulte a situação atual da operação em uma única tela.',kind:'dashboard',steps:['Confira os indicadores de alertas, efetivo, pronta resposta e sinistros.','Use os gráficos para comparar volume, situação e distribuição por base.','Clique em um indicador ou em “Ver todos” para abrir o módulo relacionado.']},
      efetivo:{intro:'Registre o plantão e consulte faltas, sanções e horas extras.',kind:'table',steps:['Escolha no menu a área que deseja consultar.','Use “Registrar novo efetivo” para informar supervisor, líder e operadores.','Abra Faltas, Sanções ou Horas extras para registrar e consultar o histórico.','Use “Gerar efetivo do dia” para copiar o texto pronto do plantão.']},
      'saida-antecipada':{intro:'Registre e acompanhe saídas antes do fim do plantão.',kind:'form',steps:['Informe colaborador, data e horários.','Descreva o motivo da saída antecipada.','Salve e consulte o registro no histórico da própria tela.']},
      'central-ocorrencias':{intro:'Acompanhe os alertas, prazos e retornos das transportadoras.',kind:'table',steps:['Use os filtros para localizar o veículo ou o alerta.','Abra um registro para conferir todos os dados e a timeline.','Solicite retorno da transportadora ou registre a tratativa permitida ao seu perfil.','Finalize somente após conferir as informações vinculadas.']},
      checklist:{intro:'Registre checklists e acompanhe resultados e validade.',kind:'form',steps:['Preencha placa, transportadora, condutor, tecnologia e validade.','Selecione o resultado do checklist.','Se estiver reprovado, informe os defeitos identificados.','Consulte o Dashboard e o Histórico pelo submenu lateral.']},
      ferias:{intro:'Programe férias e acompanhe as pessoas sob sua gestão.',kind:'calendar',steps:['Localize o colaborador disponível no seu escopo.','Informe o período de férias e confira as datas.','Salve e acompanhe o registro na listagem.']},
      assistente:{intro:'Consulte procedimentos e respostas baseadas nos manuais disponíveis.',kind:'assistant',steps:['Abra Conversa e descreva a dúvida operacional.','Confira a resposta e a referência do manual apresentada pelo sistema.','Use Manuais para consultar os documentos disponíveis.','Gestores podem abrir Dúvidas da equipe para analisar os temas recorrentes.']},
      passagem:{intro:'Prepare, receba e consulte passagens de plantão.',kind:'form',steps:['Abra “Realizar passagem” e escolha data e base.','Revise os alertas e pendências incluídos.','Conclua o envio e acompanhe em Recebidas ou Histórico.']},
      ocorrencia:{intro:'Gere um descritivo padronizado a partir do atendimento.',kind:'form',steps:['Preencha os dados do condutor, veículo, SM e contato.','Revise o tipo do alerta e a situação informada.','Gere o texto e copie o descritivo para utilização operacional.']},
      'pronta-resposta':{intro:'Registre e acompanhe acionamentos de pronta resposta.',kind:'table',steps:['Cadastre os dados do acionamento ou abra um registro originado de alerta.','Atualize equipe, status e observações durante o atendimento.','Finalize o registro quando a tratativa estiver concluída.']},
      sinistro:{intro:'Registre sinistros com dados completos e anexos.',kind:'form',steps:['Informe dados básicos, condutor, veículo e localização.','Descreva o sinistro e indique danos, feridos ou óbito quando aplicável.','Adicione imagens ou áudios necessários.','Acompanhe a situação pelo histórico de sinistros.']},
      usuarios:{intro:'Cadastre e mantenha os usuários do Smart Risk.',kind:'table',steps:['Clique em criar usuário e informe os dados obrigatórios.','Para Cliente, vincule uma transportadora.','Para Operador, vincule base e gestor.','Revise o acesso e conclua o cadastro.']},
      permissoes:{intro:'Defina quais módulos e ações cada perfil pode acessar.',kind:'settings',steps:['Selecione permissões por usuário ou perfis cadastrados.','Marque somente as páginas e ações necessárias.','Salve e peça ao usuário para entrar novamente quando o acesso mudar.']},
      'config-bases':{intro:'Cadastre bases e relacione as transportadoras atendidas.',kind:'settings',steps:['Cadastre primeiro as transportadoras.','Crie a base com nome e código.','Marque as transportadoras vinculadas e salve.']},
      ramais:{intro:'Consulte os ramais das bases usando a transportadora, a base, o setor ou o número.',kind:'table',steps:['Digite a transportadora ou base no campo de pesquisa.','Confira no cartão o nome da base e as transportadoras atendidas.','Use o setor e o número exibidos para realizar o contato.','Administradores podem cadastrar ou desativar ramais nesta mesma página.']},
      'abrir-chamado':{intro:'Abra solicitações internas e acompanhe o retorno da equipe responsável.',kind:'form',steps:['Selecione o tipo da solicitação e a prioridade.','Informe um assunto curto e descreva o que precisa.','Envie o chamado e acompanhe o status em Meus chamados.','Quando houver resposta, ela será exibida no cartão do chamado.']},
      chamados:{intro:'Receba e trate as solicitações abertas pelos usuários.',kind:'table',steps:['Use a pesquisa e o filtro de status para localizar o chamado.','Abra o tratamento e atribua um responsável.','Registre a resposta e atualize o status.','O solicitante será notificado automaticamente.']},
      'config-abas':{intro:'Mantenha as listas gerais usadas nos formulários e registros do Smart Risk.',kind:'settings',steps:['Escolha a lista que deseja alterar.','Adicione uma nova opção com um nome claro.','Remova somente opções que não devem mais aparecer nos novos registros.','As alterações passam a valer nos formulários do sistema.']},
      'config-alertas':{intro:'Configure os tipos, a criticidade e os códigos de alertas recebidos do integrador.',kind:'settings',steps:['Revise os tipos internos e defina a criticidade de cada um.','Cadastre o código informado pelo integrador e relacione-o ao tipo normalizado.','Defina se o evento está ativo, gera alerta e necessita tratamento.','Use o simulador para validar a regra antes da integração real.']}
    };
    function preview(kind,label){
      const body=kind==='dashboard'?'<i></i><i></i><i></i><i></i><b></b><b></b>':kind==='form'?'<span></span><span></span><span></span><em></em>':kind==='assistant'?'<q></q><q></q><em></em>':kind==='calendar'?'<u></u><u></u><u></u><u></u><u></u><u></u>':kind==='settings'?'<span></span><span></span><label></label><label></label>':'<strong></strong><span></span><span></span><span></span>';
      return '<div class="guide-preview guide-preview-'+esc(kind)+'" aria-label="Prévia visual da tela '+esc(label)+'"><div class="guide-preview-bar"><i></i><b>'+esc(label)+'</b></div><div class="guide-preview-side"></div><div class="guide-preview-content">'+body+'</div></div>';
    }
    host.innerHTML='<section class="guide-shell"><header class="guide-head"><div><span>AJUDA OPERACIONAL</span><h1>Guia do sistema</h1><p>Abra uma seção para ver a finalidade da tela e o passo a passo. São exibidos somente os módulos liberados no seu acesso.</p></div><label class="guide-search"><span>Pesquisar no guia</span><input id="guide-search" type="search" placeholder="Ex.: alertas, efetivo, usuário"></label></header><div class="guide-list">'+pages.map((p,index)=>{const d=docs[p.id]||{intro:'Consulte e mantenha os registros deste módulo conforme as ações liberadas em seu perfil.',kind:'table',steps:['Abra o módulo pelo menu lateral.','Use os filtros para localizar o registro desejado.','Revise as informações antes de salvar qualquer alteração.']};return '<details class="guide-module" data-guide-text="'+esc((p.label+' '+d.intro+' '+d.steps.join(' ')).toLocaleLowerCase('pt-BR'))+'" '+(index===0?'open':'')+'><summary><span class="guide-index">'+String(index+1).padStart(2,'0')+'</span><div><h2>'+esc(p.label)+'</h2><p>'+esc(d.intro)+'</p></div><span class="guide-chevron" aria-hidden="true">⌄</span></summary><div class="guide-module-body">'+preview(d.kind,p.label)+'<div class="guide-steps"><h3>Como utilizar</h3><ol>'+d.steps.map(step=>'<li>'+esc(step)+'</li>').join('')+'</ol><button type="button" class="btn btn-secondary guide-open-page" data-guide-route="'+esc(p.id)+'">Abrir esta página</button></div></div></details>';}).join('')+'<div class="empty-state guide-empty" hidden>Nenhuma orientação encontrada.</div></div></section>';
    const search=$('guide-search'),modules=Array.from(host.querySelectorAll('.guide-module')),empty=host.querySelector('.guide-empty');
    search.oninput=()=>{const query=search.value.trim().toLocaleLowerCase('pt-BR');let visible=0;modules.forEach(module=>{const show=!query||module.dataset.guideText.includes(query);module.hidden=!show;if(show)visible+=1;});empty.hidden=visible!==0;};
    host.querySelectorAll('[data-guide-route]').forEach(button=>button.onclick=()=>api.navigate(button.dataset.guideRoute));
  }
  function analytics(host){const db=api.db(),user=api.user();if(R.role(user)==='Operador'){host.innerHTML='<p class="empty-state">Área disponível para gestores.</p>';return;}const ids=new Set(R.team(user,db.users).map(u=>u.id));const queries=(db.aiQueries||[]).filter(q=>ids.has(q.userId));host.innerHTML='<section class="panel"><h1>Dúvidas da equipe</h1><p class="hint-text">'+(R.allTeams(user)?'Visão de todas as equipes':'Somente colaboradores vinculados à sua gestão')+'</p><div class="v58-chart-grid"><section><h2>Temas mais consultados</h2>'+bars(group(queries,q=>q.topic))+'</section><section><h2>Colaboradores com mais consultas</h2>'+bars(group(queries,q=>(db.users.find(u=>u.id===q.userId)||{}).nome||q.userNome))+'</section></div><h2>Perguntas mais frequentes</h2>'+bars(group(queries,q=>q.text.trim().toLocaleLowerCase('pt-BR')).slice(0,10))+'</section>';}
  return {init,dashboard,alertRules,staff,guide,analytics,modal};
})();
